# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_solution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='tasks.Task'),
        ),
    ]
